### ISSUE TITLE
有没有考虑用官方配置呢？

### ISSUE THREAD

**Issue by yihuishou** [wang926454/ShiroJwt#1]
比如 spring-boot-starter-data-redis ？

**Comment by dolyw** [comment]
之前我的示例都是使用的spring-data-redis，所以这次用的jedis，你可以查下spring-data-redis与jedis的区别

**Comment by yihuishou** [comment]
不转发到`/401`不知道行不行？

**Comment by dolyw** [comment]
在Filter没有进入到Controller如果直接抛异常，Spring全局异常解析捕获不到，返回结果是这样的
![image](https://user-images.githubusercontent.com/36805568/45811018-a625a480-bcfe-11e8-81ab-1dfb209eada3.png)
正常从/401抛出异常返回Response是这样的
![image](https://user-images.githubusercontent.com/36805568/45811110-cfdecb80-bcfe-11e8-99bc-3e2dafd15bdb.png)
解释如下: 这样直接系统报Bug了，500服务器错误，正常前端是要获取到你的返回信息的， 修改错误代码为401，所以通过/401正常返回Response的Data数据，前端才能获取到
![image](https://user-images.githubusercontent.com/36805568/45810949-7bd3e700-bcfe-11e8-9faf-47371aa2a072.png)
可以解决的办法直接在JWTFilter返回Response就好了，等会我成直接返回Response的提交你看下

**Comment by dolyw** [comment]
一直有事，今天把Shiro中鉴权失败时能直接返回401错误信息，无需再去转发弄好了，你可以看下
