### ISSUE TITLE
前端怎样将token放入到header中？，还有就是认证不通过我想直接跳转回登陆页怎么实现？

### ISSUE THREAD

**Issue by yumifen** [wang926454/ShiroJwt#12]

**Comment by dolyw** [comment]
Token放head这个代码里有呀，跳转登录页面也是看你前后端定好code，比如后端认证不通过返回504，前端判断code是504就跳转到登录页面

**Comment by yumifen** [comment]
你的前端jwt-demo我npm install 不成功，能否加一下你的微信

**Comment by wang926454** [comment]
自己看下报错解决下呗，我新的前端代码还没写，前端head放token都是请求拦截里放
![image](https://user-images.githubusercontent.com/36805568/54171412-2d392580-44b5-11e9-85bd-dc75ced745fc.png)
我github主页有我的QQ和邮件

**Comment by dolyw** [comment]
自己看下报错解决下呗，我新的前端代码还没写，前端head放token都是请求拦截里放
![image](https://user-images.githubusercontent.com/36805568/54171545-ac2e5e00-44b5-11e9-8b71-24e07cd19f21.png)
我github主页有我的QQ和邮件

**Comment by yumifen** [comment]
多谢

**Comment by yumifen** [comment]
多谢！！灰常感谢
