### ISSUE TITLE
关于Redis的问题，JedisPool 注入为空。

### ISSUE THREAD

**Issue by tujietg** [wang926454/ShiroJwt#18]
你好，大佬。我这边跑大佬的代码出现了一个问题，JedisPool为空。

**Comment by dolyw** [comment]
取jedis实例报空指针吗？应该是你初始化没连接上redis

**Comment by tujietg** [comment]
大佬，我这边初始化没有问题。输出了 “初始化Redis连接池JedisPool成功!”

**Comment by dolyw** [comment]
这个初始化无效的，只有能获取实例才是连接正确的

**Comment by tujietg** [comment]
好的 大佬 ，我这边看一下，谢谢你啦～

**Comment by tujietg** [comment]
大佬，我通过使用JedisUtil的构造方法是可以连接到redis的，但是不知道没找到为什么用你那种注入的方式就会有空指针异常的问题。（我比较菜～）

**Comment by dolyw** [comment]
你是连接的本地的redis吗？密码有设置吗，在JedisConfig里设置下

**Comment by tujietg** [comment]
是连接服务器的，大佬，在JedisConfig直接设置解决了问题，现在已经跑通了。谢谢大佬～
