### ISSUE TITLE
跨域sso问题

### ISSUE THREAD

**Issue by mrqinlin** [wang926454/ShiroJwt#19]
sso的各个系统在不同的域下，不同域下cookie vue_admin_template_token没法共享，有没有好的解决办法？

**Comment by dolyw** [comment]
你的多个系统应该可以通过二级域名共享Cookie吧

**Comment by mrqinlin** [comment]
@wang926454 sso的场景是一级域名不同，在不同的域下

**Comment by dolyw** [comment]
你这不是为难胖虎我吗？这就有点麻烦了，我没遇到过，也只能查资料问人了，你自己也先查查资料吧

**Comment by mrqinlin** [comment]
@wang926454 哈哈，多谢了！
一种可行的方式应该是这样：
1、统一认证系统假如叫sso，不同域子系统a被访问，先检查a的token是否存在，存在则调用sso的token权限检查，决定是否重定向至sso的统一登录页面。 
2、不存在则携带a的重定向url重定向至sso的统一登录页面，登录成功，返回token写至a的域下。
