### ISSUE TITLE
redis的password被重置为null

### ISSUE THREAD

**Issue by Edinjohn** [wang926454/ShiroJwt#20]
![image](https://user-images.githubusercontent.com/16401814/57440416-91405600-727a-11e9-8fd0-b86b07887606.png)
报错信息如下
![image](https://user-images.githubusercontent.com/16401814/57440460-a7e6ad00-727a-11e9-8a6c-c71ad9fa28e3.png)
我给自己的redis设了一个密码，但是在config.properties配置的redis.password值并不能带入到对象中去，导致验证失败。（其他值如Host，port是正确的）
你可以试一下给redis设置个密码

**Comment by dolyw** [comment]
![image](https://user-images.githubusercontent.com/36805568/57440919-77ebd980-727b-11e9-9565-02c0ed30b017.png)

**Comment by dolyw** [comment]
你在这里加下判断吧，判断password是否为空字符串，为空就执行下面那个，不为空执行上面那个(因为redis密码如果为空的话password不传null值，而传空字符串是连接不上的)，改了可以提一个PR，我合并下，好多人都是redis连接的问题
