### ISSUE TITLE
如果是微服务的话，是不是每个微服务都的写一套这样的shiro?

### ISSUE THREAD

**Issue by lbin2012** [wang926454/ShiroJwt#22]
我参考了你的代码，把用户认证单独放在一个微服务里，那这样其他微服务是不是都要有token认证和鉴权？

**Comment by lbin2012** [comment]
token的刷新问题，如果前面一个请求刚好刷新了token，redis里的refresh_token刷新了，这时候刚好来了一个老的请求，岂不是会认证失败跳转到首页

**Comment by dolyw** [comment]
微服务的话网关统一鉴权吧，这样就不要每个都写，或者还有更好的方式，你可以查资料找找

**Comment by dolyw** [comment]
#14 重复请求会不会生成多个token  你看下这个，对于这块说同时发出请求，第一个请求刷新Token的问题，我大概想了一下，查了一些资料，看了下好的实现方式是这样的，下面有链接
