### ISSUE TITLE
在JwtFilter中为什么每次请求都需要调用shiro的subject.login ？

### ISSUE THREAD

**Issue by HackenHYJ** [wang926454/ShiroJwt#24]
在JwtFilter中为什么每次请求都需要调用shiro的subject.login ？
有没有办法一次性登陆后续的接口不用登陆？ 因为token从实际意义来看，也只能是已登陆用户才能持有的凭证。

**Comment by dolyw** [comment]
你搜索下token和session的区别，你这样的想法是想把token做成session了
