### ISSUE TITLE
关于ExceptionAdvice的作用

### ISSUE THREAD

**Issue by hanzhenchaoGit** [wang926454/ShiroJwt#25]
ExceptionAdvice这个全局异常捕获不起作用吧  这个捕获应该只对进入controller的请求出错抛出的异常才起作用 才能拦截到吧 对于JwtFilter里面抛出的异常都是处理不到的

**Comment by dolyw** [comment]
你可以自己查下Spring的全局捕获机制看下就清楚了，一般他这个都是用来捕获下面三种情况：
1. 在进入Controller之前，譬如请求一个不存在的地址，404
2：在执行@RequestMapping时，进入逻辑处理阶段前，譬如传的参数类型错误，校验错误
3：以上都正常时，在Controller里执行逻辑代码时出的异常，例如空指针异常，数组越界异常
