### ISSUE TITLE
mysql数据库文件在哪里？

### ISSUE THREAD

**Issue by fanyiqiang2015** [wang926454/ShiroJwt#27]
在项目中没有找到数据库初始化文件

**Comment by dolyw** [comment]
![image](https://user-images.githubusercontent.com/36805568/69392879-7747fb80-0d12-11ea-846b-78e4d453172c.png)

**Comment by fanyiqiang2015** [comment]
thank you,我是在码云上看到的这个项目，码云里没有，我以为两边是同步的

**Comment by dolyw** [comment]
![image](https://user-images.githubusercontent.com/36805568/69393086-1d940100-0d13-11ea-9335-1ec439322646.png)

**Comment by dolyw** [comment]
是同步的:yum:
