### ISSUE TITLE
shiro会给token前加上Bearer字符串

### ISSUE THREAD

**Issue by disabilites** [wang926454/ShiroJwt#30]
`String token = (String)authenticationToken.getCredentials();`
这里获取的token前会被加上Bearer

原本应该是：
`eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJjdXJyZW50VGltZU1pbGx ……`

现在
`Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJjdXJyZW50VGltZU1pbGx ……`

**Comment by dolyw** [comment]
不会的哦，这个是你自己调用工具的问题，你检测下你调用接口的工具吧

**Comment by disabilites** [comment]
谢谢，是 postman 给我加上的😂

**Comment by dolyw** [comment]
嗯嗯，看到这个Bearer我就猜是这样，哈哈哈
