### ISSUE TITLE
token并发刷新问题

### ISSUE THREAD

**Issue by yuhaoxiao** [wang926454/ShiroJwt#31]
示例代码中并发请求判断在有效时间内之后，登陆依然用的是旧的token（this.getSubject(request,response).login(oldToken)），这样shiro不是会继续报出token失效的异常吗，依然会登陆不成功

**Comment by dolyw** [comment]
> 示例代码中并发请求判断在有效时间内之后，登陆依然用的是旧的token（this.getSubject(request,response).login(oldToken)），这样shiro不是会继续报出token失效的异常吗，依然会登陆不成功

没理解你的意思，能详细贴下代码，和你思考的流程吗，可以加下QQ群交流: 779168604

**Comment by dolyw** [comment]
> 示例代码中并发请求判断在有效时间内之后，登陆依然用的是旧的token（this.getSubject(request,response).login(oldToken)），这样shiro不是会继续报出token失效的异常吗，依然会登陆不成功

理解你意思了，不是说了加个过渡期吗，这个过渡期内Token就是有效的啊
