### ISSUE TITLE
登陆验证时解密异常，密钥有误

### ISSUE THREAD

**Issue by pgm-sup** [wang926454/ShiroJwt#4]
![_20181006170315](https://user-images.githubusercontent.com/29563530/46569593-04eb4f00-c98a-11e8-9824-e16f840a1732.png)

**Comment by dolyw** [comment]
![image](https://user-images.githubusercontent.com/36805568/46569856-c8215700-c98d-11e8-90d7-54066f109ae1.png)
没有问题呀，是不是你调用有问题

**Comment by dolyw** [comment]
我规范一下参数调用方式吧，等明天弄好，你重新看下

**Comment by pgm-sup** [comment]
能看看你的登录传参吗？

**Comment by pgm-sup** [comment]
> ![image](https://user-images.githubusercontent.com/36805568/46569856-c8215700-c98d-11e8-90d7-54066f109ae1.png)
> 没有问题呀，是不是你调用有问题

能不能看一下你的登录传参，我这边重新拉了一下你的代码，还是这样的，我测试过密码加密都没有问题，能正常返回，可是拿着返回的结果去解密就不行了，就报BadPaddingException这样一个异常，我也查阅了大量资料，最后猜测是不是环境问题，我是用的linux环境

**Comment by pgm-sup** [comment]
> > ![image](https://user-images.githubusercontent.com/36805568/46569856-c8215700-c98d-11e8-90d7-54066f109ae1.png)
> > 没有问题呀，是不是你调用有问题
> 
> 能不能看一下你的登录传参，我这边重新拉了一下你的代码，还是这样的，我测试过密码加密都没有问题，能正常返回，可是拿着返回的结果去解密就不行了，就报BadPaddingException这样一个异常，我也查阅了大量资料，最后猜测是不是环境问题，我是用的linux环境

**Comment by pgm-sup** [comment]
> > > ![image](https://user-images.githubusercontent.com/36805568/46569856-c8215700-c98d-11e8-90d7-54066f109ae1.png)
> > > 没有问题呀，是不是你调用有问题
> > 
> > 
> > 能不能看一下你的登录传参，我这边重新拉了一下你的代码，还是这样的，我测试过密码加密都没有问题，能正常返回，可是拿着返回的结果去解密就不行了，就报BadPaddingException这样一个异常，我也查阅了大量资料，最后猜测是不是环境问题，我是用的linux环境

**Comment by pgm-sup** [comment]
你好，问题找到了，SecureRandom 实现完全随操作系统本身的內部状态，除非调用方在调用 getInstance 方法，然后调用 setSeed 方法；该实现在 windows 上每次生成的 key 都相同，但是在 solaris 或部分 linux 系统上则不同，可以这样修改`            SecureRandom secureRandom = SecureRandom.getInstance("SHA1PRNG");
            secureRandom.setSeed(Base64ConvertUtil.decode(encrypAESKey).getBytes());
            keygen.init(128, secureRandom);`

**Comment by wang926454** [comment]
发现了，你可以提交一下

**Comment by dolyw** [comment]
发现了，你可以Fork提交一下
