### ISSUE TITLE
JwtFilter 中的 refreshToken 方法含有 TODO 标记

### ISSUE THREAD

**Issue by chunsiyang** [wang926454/ShiroJwt#9]
该方法是还没有完成么，还是完成后没有去除 TODO 标记

**Comment by dolyw** [comment]
完成后没有去除 TODO 标记

**Comment by dolyw** [comment]
你fork去除提交下吧

**Comment by chunsiyang** [comment]
> 你叉去除提交下吧

在做了，有个疑问想请教下，refreshToken 方法中现在只实现了对 未过期AccessToken 的刷新处理，那么AccessToken过期但是RefreshToken未过期的刷新操作是在哪里实现的呢，谢谢啦

**Comment by dolyw** [comment]
都是在同一个地方实现的呀
![image](https://user-images.githubusercontent.com/36805568/49195122-c047c700-f3c0-11e8-8cb3-827d8b485782.png)
认证时捕获到异常是AccessToken过期的异常也进行刷新

**Comment by dolyw** [comment]
![image](https://user-images.githubusercontent.com/36805568/49195461-2c76fa80-f3c2-11e8-8570-5af3e7bf690a.png)

**Comment by chunsiyang** [comment]
好的，谢谢了
